### ISSUE TITLE
Ship the flamegraph as part of base VS Code

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-js-profile-visualizer#14]
This is more a question: are there plans to include the flamegraph stuff inside the core VS Code product, without the need for an extension installation? I think that would be nice.

**Comment by connor4312** [comment]
Sorry for the late response, this issue came in as js-debug went default on VS Code and I was dealing with loads of other issues 🙂 

At the moment, we don't plan to make the flame graph built-in. We include the table and have the little 🔥 icon on the right-hand side that 'upsells' the flame graph extension.
