### ISSUE TITLE
Is there an assumption about ProfileNode.id?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-js-profile-visualizer#4]
It seems to me that there is some assumption about consecutive values for `ProfileNode.id` built into the extension? Could that be relaxed, so that arbitrary numbers can be used there, i.e. numbers that are not counting from 1? If so, we could use the internal ids from Julia, which are all over the place, without another conversion step.

Not the end of the world, but it seems the spec is not formulating a requirement on what these ids should be, other than numbers.

**Comment by connor4312** [comment]
We could. The incrementing IDs are used to be able to do quick operations and cross-referencing in the model, but we could have a step when we build the model to force them to be auto-incrementing. We already do a transformation to make them by 0-based instead of the 1-based IDs that chrome gives us out of the box.

Code pointer:

https://github.com/microsoft/vscode-js-profile-visualizer/blob/1db1edec339ce3b8f8a15b66ab55b6f9398dd97c/packages/vscode-js-profile-core/src/cpu/model.ts#L221-L261

**Comment by vchuravy** [comment]
Yeah for Julia the most convenient format would be arbitrary, since that would allow us to just use instruction pointers.

**Comment by connor4312** [comment]
Added

**Comment by davidanthoff** [comment]
Cool, thanks!
